<<<<<<< HEAD
=======
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH


>>>>>>> a92982b (2027-07-11)
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="random"

plugins=( 
<<<<<<< HEAD
=======
    git
>>>>>>> a92982b (2027-07-11)
    archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
)

<<<<<<< HEAD
load-kitty-silently(){
	source $ZSH/oh-my-zsh.sh
} &> /dev/null 


#pokemon-colorscripts --no-title -r

   #Cursor changing color after every command
=======
source $ZSH/oh-my-zsh.sh

# Check archlinux plugin commands here
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/archlinux


# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos
pokemon-colorscripts --no-title -r

### From this line is for pywal-colors
# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
# Not supported in the "fish" shell.
(cat ~/.cache/wal/sequences &)

# Alternative (blocks terminal for 0-3ms)
cat ~/.cache/wal/sequences

#**********************************************************
    #Cursor changing color after every command
>>>>>>> a92982b (2027-07-11)
cursor_change_color(){
    hex=$(openssl rand -hex 3)
    echo -ne "\e]12;#$hex\a"
}

function postcmd(){
    cursor_change_color
}

precmd_functions+=(postcmd)

<<<<<<< HEAD
alias todo='vim /mnt/KSS/Studies/todo/todo'
alias todod='cd /mnt/KSS/Studies/todo/'
alias spm='cd /mnt/KSS/Studies/SPM/'
alias rvce='cd /mnt/KSS/Studies/RVCE/'
alias backups='cd /mnt/KSS/Back_Ups'
alias docs='cd /mnt/KSS/Documents/'
alias scripts='cd ~/scripts'
alias media='cd /mnt/KSS/Media/'
alias songs='cd /mnt/KSS/Media/Songs/'
alias playsongs='mpv /mnt/KSS/Media/Songs/* --shuffle'
alias hypr='cd ~/.config/hypr'
alias zsh='vim ~/.zshrc'
alias gs='git status'
alias gph='git push'
alias gpl='git pull'
alias towatch='mpv /mnt/KSS/Media/towatch/* --shuffle'
alias towatchd='cd /mnt/KSS/Media/towatch'
alias tolisten='mpv /mnt/KSS/Media/tolisten/* --shuffle'
alias tolistend='cd /mnt/KSS/Media/tolisten/'
alias enco='bluetoothctl connect 2C:FD:B4:7E:65:6A'
alias poco='bluetoothctl connect 10:3F:44:8B:06:F2'
alias down='cd ~/Downloads'
alias wallpaper='cd ~/Pictures/wallpapers/'
alias waldown='find ~/Downloads -type f \( -name "*.mp4" -o -name "*.jpeg" -o -name "*.jpg" -o -name "*.png" \) -exec mv {} ~/Pictures/wallpapers/ \;'
alias zshup='cp ~/.zshrc ~/dot-files/.zshrc'
alias ran='ranger'
alias calc='deepin-calculator'
alias archup='yay -Scc & sudo pacman -Scc && sudo pacman -Syu'
alias ttw='rsync -achPz --update /mnt/KSS/Media/towatch/* phone:/storage/E0BE-1F10/towatch/'
alias ttl='rsync -avhPz --update /mnt/kSS/Media/tolisten/* phone:/storage/E0BE-1F10/tolisten'
alias todoup='cd /mnt/KSS/Studies/todo/ && gc && git push todo main'
alias tododown='cd /mnt/KSS/Studies/todo/ && git pull todo main'
alias cod='vim /mnt/KSS/Studies/SPM/codes'
alias ref='sudo reflector --country 'India' --latest 5 --sort rate --save /etc/pacman.d/mirrorlist'
alias ubuntuup='sudo apt update && sudo apt upgrade && sudo pkg update && sudo apt upgrade && sudo apt full-upgrade && sudo apt autoremove && sudo apt autoclean && sudo apt clean'
alias lkey='gpg --list-keys --keyid-format long'
alias lskey='gpg --list-secret-keys --keyid-format long'
alias de='bash de'
alias en='bash en'
alias l='ls -al --color=never'
alias lc='ls -al'
alias dotpush='cd ~/dot-files && git commit -a --reuse-message=HEAD && gph '
alias dotpull='cd ~/dot-files && git pull dots hyprland'
alias zshdown='cp ~/dot-files/.zshrc ~/.zshrc && source ~/.zshrc'
alias chgit=" git config --global user.name "Surajk013" && git config --global user.email "surajsinghk013@gmail.com" "
alias cve='rvce && cd CVE'
alias lap='mosh laptop'
alias pn='mosh phone'
alias pc='mosh pc'
alias gnu='rvce && cd ../GNU'
alias neo='neofetch'
alias uwu='uwufetch'
alias fast='fastfetch'
alias gnu='cd /mnt/KSS/Studies/GNU/'
alias pf='pfetch'
alias gc=" git commit -am "$(date '+%Y-%m-%d %H-%M-%S')" "


export PATH="$HOME/.local/bin:$PATH"




load-kitty-silently
=======
#**********************************************************

# To add support for TTYs this line can be optionally added.
#source ~/.cache/wal/colors-tty.

# Add ~/.local/bin to PATH (auto-generated by pokeget installer)
export PATH="$HOME/.local/bin:$PATH"

#alias full-upgrade='sudo'

alias rr='onlyoffice-desktopeditors & code & pavucontrol & qutebrowser'
>>>>>>> a92982b (2027-07-11)
